/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable quotes */
/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface DBbanned {
  'banEnd': Date | null;
  'banStart': Date | null;
  'userId': string;
}
export interface DBevent {
  'color': string;
  'createdDateTime': Date;
  'description': string;
  'endDateTime': Date;
  'endedDateTime': Date | null;
  'hostId': string;
  'id': number;
  'isChatEnabled': boolean;
  'latitude': number;
  'longitude': number;
  'shouldHideAfterStartDate': boolean;
  'startDateTime': Date;
  'title': string;
  'updatedDateTime': Date;
}
export interface DBeventAttendance {
  'eventId': number;
  'joinedDateTime': Date;
  'role': 'hosting'|'attending';
  'userId': string;
}
export interface DBEventAttendeeCountView {
  'attendeeCount': number;
  'id': number;
}
export interface DBEventAttendeesView {
  'eventId': number;
  'userIds': string | null;
}
export interface DBeventReports {
  'eventOwnerId': string;
  'eventReported': number;
  'reportDate': Date;
  'reportingReason': 'Spam'|'Harassment'|'Hate Speech'|'Violence'|'Scam or fraud'|'Suicide or self-harm'|'False information'|'Sale of illegal or regulated goods'|'Other';
  'userReporting': string;
}
export interface DBlocation {
  'city': string | null;
  'country': string | null;
  'createdDateTime': Date;
  'isoCountryCode': string | null;
  'latitude': number;
  'longitude': number;
  'name': string | null;
  'postalCode': string | null;
  'region': string | null;
  'street': string | null;
  'streetNumber': string | null;
  'timezoneIdentifier': string;
}
export interface DBpushTokens {
  'id': number;
  'platformName': 'apple'|'android';
  'pushToken': any | null;
  'userId': string;
}
export interface DBTifEventView {
  'city': string | null;
  'color': string;
  'country': string | null;
  'createdDateTime': Date;
  'description': string;
  'endDateTime': Date;
  'endedDateTime': Date | null;
  'hasArrived': boolean;
  'hostHandle': string;
  'hostId': string;
  'hostUsername': string;
  'id': number;
  'isChatEnabled': boolean;
  'isoCountryCode': string | null;
  'latitude': number;
  'longitude': number;
  'placemarkName': string | null;
  'postalCode': string | null;
  'region': string | null;
  'shouldHideAfterStartDate': boolean;
  'startDateTime': Date;
  'street': string | null;
  'streetNumber': string | null;
  'timezoneIdentifier': string | null;
  'title': string;
  'updatedDateTime': Date;
}
export interface DBuser {
  'bio': string | null;
  'createdDateTime': Date;
  'handle': string;
  'id': string;
  'name': string;
  'profileImageURL': string | null;
  'updatedDateTime': Date;
}
export interface DBuserArrivals {
  'arrivedDateTime': Date;
  'latitude': number;
  'longitude': number;
  'userId': string;
}
export interface DBuserRelations {
  'fromUserId': string;
  'status': 'friends'|'friend-request-pending'|'blocked';
  'toUserId': string;
  'updatedDateTime': Date;
}
export interface DBuserReports {
  'reportDate': Date;
  'reportingReason': 'Spam'|'Harassment'|'Hate Speech'|'Violence'|'Scam or fraud'|'Suicide or self-harm'|'False information'|'Sale of illegal or regulated goods'|'Other';
  'userReported': number;
  'userReporting': number;
}
export interface DBuserSettings {
  'isAnalyticsEnabled': boolean;
  'isChatNotificationsEnabled': boolean;
  'isCrashReportingEnabled': boolean;
  'isEventNotificationsEnabled': boolean;
  'isFriendRequestNotificationsEnabled': boolean;
  'isMentionsNotificationsEnabled': boolean;
  'updatedDateTime': Date | null;
  'userId': string;
}
