name: Build API Lambda

on:
  workflow_call:
    outputs:
      zip-path:
        description: "API Lambda zip"
        value: ${{ jobs.build.outputs.zip-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      zip-path: ${{ steps.set-output.outputs.zip-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install backend utils dependencies
        run: |
          cd TiFBackendUtils
          npm ci
      
      - name: Build backend utils js
        run: |
          cd TiFBackendUtils
          npm run build
      
      - name: Remove backend utils dev dependencies
        run: |
          cd TiFBackendUtils
          jq 'del(.scripts.postinstall)' package.json > temp.json && mv temp.json package.json
          npm ci --omit=dev
      
      - name: Package backend utils
        run: |
          cd TiFBackendUtils
          shopt -s extglob
          cp -R node_modules dist/
          cp *.json dist/
          cd dist
          npm pack

      - name: Install dependencies
        run: |
          cd APILambda
          npm ci
          npm install ../TiFBackendUtils/dist/TiFBackendUtils-1.0.0.tgz

      - name: Build the project
        run: |
          cd APILambda
          npm run build
      
      - name: Remove dev dependencies
        run: |
          cd APILambda
          npm ci --omit=dev

      - name: Zip the project
        run: |
          cd APILambda
          shopt -s extglob
          cp -R node_modules dist/
          cp *.json dist/
          cd dist
          zip -r ../dist.zip .
      
      - name: Set output path
        id: set-output
        run: echo "::set-output name=zip-path::./APILambda/dist.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-lambda
          path: ./APILambda/dist.zip