name: Build API Lambda

on:
  workflow_call:
    outputs:
      zip-path:
        description: "API Lambda zip"
        value: ${{ jobs.build.outputs.zip-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      zip-path: ${{ steps.set-output.outputs.zip-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install TiFBackendUtils dependencies
        run: |
          cd TiFBackendUtils
          npm ci
      
      - name: Remove TiFBackendUtils postinstall
        run: |
          cd TiFBackendUtils
          jq 'del(.scripts.postinstall)' package.json > temp.json && mv temp.json package.json

      - name: Install project dependencies
        run: |
          cd APILambda
          npm ci
          
      - name: Build the project
        run: |
          cd APILambda
          npm run build
          
      - name: Build TiFBackendUtils js
        run: |
          cd TiFBackendUtils
          npm run build
      
      - name: Remove TiFBackendUtils dev dependencies
        run: |
          cd TiFBackendUtils
          npm prune --production
      
      - name: Package TiFBackendUtils
        run: |
          cd TiFBackendUtils
          npm pack
          
      - name: Install dependencies
        run: |
          cd APILambda
          npm install ../TiFBackendUtils/TiFBackendUtils-1.0.0.tgz
      
      - name: Remove dev dependencies
        run: |
          cd APILambda
          npm prune --production

      - name: Zip the project
        run: |
          cd APILambda
          zip -r dist.zip .
      
      - name: Set output path
        id: set-output
        run: echo "::set-output name=zip-path::./APILambda/dist.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-lambda
          path: ./APILambda/dist.zip