name: Build and Deploy Geocoding Pipeline to AWS Lambda

on:
  push:
    branches:
      - main 

jobs:
  build:
    uses: ./.github/workflows/build_geocoder.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy_geocoder.yml
    with:
      stage: "prod"
