name: Build and Deploy API to AWS Lambda

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:  
  build:
    uses: ./.github/workflows/build_api.yml
    secrets: inherit
  
  deploy:
    needs: build
    uses: ./.github/workflows/deploy_api.yml
    secrets: inherit
    with:
      stage: "staging"