name: Build and Deploy to AWS Lambda Layer

on:
  push:
    branches:
      - main
      - development 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Remove dev dependencies
        run: cd dist && npm prune --production

      - name: Zip the project
        run: |
          shopt -s extglob
          cp -R !(test|.github|dist|*.ts|APILambda|GeocodingLambda) dist/nodejs/
          cd dist
          zip -r ../dist.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda Layer
        run: |
          OUTPUT=$(aws lambda publish-layer-version --layer-name tifSharedBackendResources --zip-file fileb://dist.zip)
          echo "LAYER_VERSION_ARN=$(echo $OUTPUT | jq -r '.LayerVersionArn')" >> $GITHUB_ENV

      - name: Update Lambda function to use new layer version
        run: |
          aws lambda update-function-configuration --function-name lambdaSQLRoute --layers ${{ env.LAYER_VERSION_ARN }}
          aws lambda update-function-configuration --function-name geocodingPipeline --layers ${{ env.LAYER_VERSION_ARN }}
