name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - development 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Replace @layer/ alias
        run: |
          npm install -g replace
          replace '@layer/' '/opt/nodejs/' ./ -r --include="*.ts,*.tsx"

      - name: Install dependencies
        run: npm install -g typescript
      
      - name: Build the project
        run: tsc ./GeocodingLambda/*.ts

      - name: Zip the project
        run: |
          cd GeocodingLambda
          zip -r ./dist.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name geocodingPipeline --zip-file fileb://GeocodingLambda/dist.zip
