name: Build and Deploy Geocoding Pipeline to AWS Lambda

on:
  push:
    branches:
      - main
      - development 

jobs:
  build:
    uses: ./.github/workflows/build_geocoder.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: geocoding-lambda
      
      - name: Update AWS Lambda env variables
        run: |
          aws lambda update-function-configuration \
            --function-name geocodingPipeline \
            --environment "Variables={\
              DATABASE_HOST=${{ secrets.DATABASE_HOST }},\
              DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }},\
              DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}\
            }"

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name geocodingPipeline --zip-file fileb://geocoding-lambda/dist.zip
          while true; do
              update_status=$(aws lambda get-function --function-name geocodingPipeline | jq -r '.Configuration.LastUpdateStatus')

              if [[ "$update_status" == "Successful" ]]; then
                  echo "Update completed successfully."
                  break
              elif [[ "$update_status" == "Failed" ]]; then
                  echo "Update failed."
                  exit 1
              else
                  echo "Update in progress. Waiting..."
                  sleep 10
              fi
          done
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            stageName="prod"
            VERSION_NUMBER=$(aws lambda publish-version --function-name geocodingPipeline | jq -r '.Version')
            aws lambda update-alias --function-name geocodingPipeline --name prod --function-version $VERSION_NUMBER
          else
            stageName="staging"
          fi
