name: Lint and Typecheck Project

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Check ESLint
        run: |
          npx eslint . --fix
    
      - name: Check Typescript
        run: |
          npx tsc --noEmit
