name: Lint and Compile Project

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: lint-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Check ESLint
        run: |
          npm run lint
