name: Lint Project

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Check ESLint
        run: |
          npx eslint . --fix
