name: Test Geocoder Pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: yourpassword
          MYSQL_DATABASE: devTest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root --password=yourpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: yourpassword
      DATABASE_NAME: devTest
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_LAMBDA_FUNCTION_NAME: geocodingPipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - name: Run tests
        run: |
          cd GeocodingLambda
          npm run test:ci
  
  build:
    needs: test
    uses: ./.github/workflows/build_geocoder.yml
    secrets: inherit
  
  deploy:
    needs: build
    uses: ./.github/workflows/deploy_geocoder.yml
    secrets: inherit
    with:
      stage: "stagingTest"