name: Test Utils

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: testUtils-${{ github.head_ref }}
      cancel-in-progress: true

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: tif
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: tif
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ABLY_KEY: ${{ secrets.ABLY_KEY }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
      AWS_LAMBDA_FUNCTION_NAME: lambdaSQLRoute

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          cd TiFBackendUtils
          npm run test:ci

      - name: Build backend utils js
        run: |
          cd TiFBackendUtils
          npm run build